version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install gradle -y

      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set default.region us-east-1
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            gradle build
            cd build
            pwd
            ls -al
            mv lambda-0.0.1.zip lambda.zip
            ls -al
            cd ..
            pwd
      - run:
          name: Upload Artifact to S3
          command: |
            cd build
            aws s3 sync distributions s3://${S3_CODEDEPLOY_BUCKET}
      - run:
          name: Make CodeDeploy API call
          command: |
            aws lambda update-function-code\
                 --region ${AWS_REGION}\
                 --function-name demo\
                 --s3-bucket=${S3_CODEDEPLOY_BUCKET}\
                 --s3-key lambda-0.0.1.zip